[workspace.package]
authors = ["Nigel"]
homepage = "https://www.jetneuron.com/"
edition = "2024"

[workspace]
members = [
    "crates/fusion-derive",
    "crates/fusion-streaming",
    "crates/fusion-unit-datafusion",
    "crates/fusion-unit-excel", "crates/fusion-unit-net", "crates/fusion-unit-redis",
    "crates/fusion-unit-sdk",
    "crates/fusion-unit-ssh",
    "crates/fusion-unit-tests",
    "crates/fusion-unit-universal-fs",
    "crates/scripts/fusion-script-ts"]
resolver = "3"

[profile.dev]
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = "fat"
debug = false
