[workspace.package]
authors = ["Nigel"]
homepage = "https://www.jetneuron.com/"
edition = "2024"

[workspace]
members = [
    "crates/fusion-derive",
    "fusion-runtime",
    "crates/fusion-streaming",
    "crates/fusion-unit-sdk",
    "tests/fusion-unit-tests",
    "crates/fusion-plugins/capability/fusion-capability-example",
    "crates/fusion-plugins/capability/fusion-capability-datafusion",
    "crates/fusion-plugins/capability/fusion-capability-redis",
    "crates/fusion-plugins/units/fusion-unit-excel",
    "crates/fusion-plugins/units/fusion-unit-net",
    "crates/fusion-plugins/units/fusion-unit-datafusion",
    "crates/fusion-plugins/units/fusion-unit-datafusion/providers/fusion-unit-datafusion-sqlite",
    "crates/fusion-plugins/units/fusion-unit-redis",
    "crates/fusion-plugins/units/fusion-unit-ssh",
    "crates/fusion-plugins/units/fusion-unit-universal-fs",
    "crates/scripts/fusion-script-ts"]
resolver = "3"

[workspace.dependencies]
fusion-streaming = { path = "crates/fusion-streaming" }
fusion-unit-sdk = { path = "crates/fusion-unit-sdk" }
fusion-unit-excel = { path = "crates/fusion-plugins/units/fusion-unit-excel" }
fusion-unit-ssh = { path = "crates/fusion-plugins/units/fusion-unit-ssh" }
fusion-unit-redis = { path = "crates/fusion-plugins/units/fusion-unit-redis" }
fusion-unit-net = { path = "crates/fusion-plugins/units/fusion-unit-net" }
fusion-unit-universal-fs = { path = "crates/fusion-plugins/units/fusion-unit-universal-fs" }
fusion-derive = { path = "crates/fusion-derive" }
fusion-script-ts = { path = "crates/scripts/fusion-script-ts" }
fusion-capability-datafusion = { path = "crates/fusion-plugins/capability/fusion-capability-datafusion" }
fusion-capability-example = { path = "crates/fusion-plugins/capability/fusion-capability-example" }
fusion-unit-datafusion = { path = "crates/fusion-plugins/units/fusion-unit-datafusion" }

[profile.dev]
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = "fat"
debug = false
