// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `transfer.proto`
// Generated for lite runtime

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:transfer.Frame)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Frame {
    // message fields
    // @@protoc_insertion_point(field:transfer.Frame.offset)
    pub offset: u64,
    // @@protoc_insertion_point(field:transfer.Frame.columns)
    pub columns: ::std::vec::Vec<Column>,
    // @@protoc_insertion_point(field:transfer.Frame.mask)
    pub mask: u32,
    // @@protoc_insertion_point(field:transfer.Frame.source)
    pub source: ::std::string::String,
    // @@protoc_insertion_point(field:transfer.Frame.raw)
    pub raw: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:transfer.Frame.barrier_ref)
    pub barrier_ref: u64,
    // special fields
    // @@protoc_insertion_point(special_field:transfer.Frame.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Frame {
    fn default() -> &'a Frame {
        <Frame as ::protobuf::Message>::default_instance()
    }
}

impl Frame {
    pub fn new() -> Frame {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Frame {
    const NAME: &'static str = "Frame";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.offset = is.read_uint64()?;
                },
                18 => {
                    self.columns.push(is.read_message()?);
                },
                24 => {
                    self.mask = is.read_uint32()?;
                },
                34 => {
                    self.source = is.read_string()?;
                },
                42 => {
                    self.raw = is.read_bytes()?;
                },
                48 => {
                    self.barrier_ref = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.offset != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.offset);
        }
        for value in &self.columns {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.mask != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.mask);
        }
        if !self.source.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.source);
        }
        if !self.raw.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.raw);
        }
        if self.barrier_ref != 0 {
            my_size += ::protobuf::rt::uint64_size(6, self.barrier_ref);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.offset != 0 {
            os.write_uint64(1, self.offset)?;
        }
        for v in &self.columns {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.mask != 0 {
            os.write_uint32(3, self.mask)?;
        }
        if !self.source.is_empty() {
            os.write_string(4, &self.source)?;
        }
        if !self.raw.is_empty() {
            os.write_bytes(5, &self.raw)?;
        }
        if self.barrier_ref != 0 {
            os.write_uint64(6, self.barrier_ref)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Frame {
        Frame::new()
    }

    fn clear(&mut self) {
        self.offset = 0;
        self.columns.clear();
        self.mask = 0;
        self.source.clear();
        self.raw.clear();
        self.barrier_ref = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Frame {
        static instance: Frame = Frame {
            offset: 0,
            columns: ::std::vec::Vec::new(),
            mask: 0,
            source: ::std::string::String::new(),
            raw: ::std::vec::Vec::new(),
            barrier_ref: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

// @@protoc_insertion_point(message:transfer.Column)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Column {
    // message fields
    // @@protoc_insertion_point(field:transfer.Column.index)
    pub index: u32,
    // @@protoc_insertion_point(field:transfer.Column.field)
    pub field: ::std::string::String,
    // @@protoc_insertion_point(field:transfer.Column.dt)
    pub dt: ::protobuf::EnumOrUnknown<DataType>,
    // @@protoc_insertion_point(field:transfer.Column.is_null)
    pub is_null: bool,
    // @@protoc_insertion_point(field:transfer.Column.i32_val)
    pub i32_val: i32,
    // @@protoc_insertion_point(field:transfer.Column.i64_val)
    pub i64_val: i64,
    // @@protoc_insertion_point(field:transfer.Column.f64_val)
    pub f64_val: f64,
    // @@protoc_insertion_point(field:transfer.Column.f32_val)
    pub f32_val: f32,
    // @@protoc_insertion_point(field:transfer.Column.str_val)
    pub str_val: ::std::string::String,
    // @@protoc_insertion_point(field:transfer.Column.bool_val)
    pub bool_val: bool,
    // @@protoc_insertion_point(field:transfer.Column.bytes_val)
    pub bytes_val: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:transfer.Column.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Column {
    fn default() -> &'a Column {
        <Column as ::protobuf::Message>::default_instance()
    }
}

impl Column {
    pub fn new() -> Column {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for Column {
    const NAME: &'static str = "Column";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.index = is.read_uint32()?;
                },
                18 => {
                    self.field = is.read_string()?;
                },
                24 => {
                    self.dt = is.read_enum_or_unknown()?;
                },
                32 => {
                    self.is_null = is.read_bool()?;
                },
                40 => {
                    self.i32_val = is.read_int32()?;
                },
                48 => {
                    self.i64_val = is.read_int64()?;
                },
                57 => {
                    self.f64_val = is.read_double()?;
                },
                69 => {
                    self.f32_val = is.read_float()?;
                },
                74 => {
                    self.str_val = is.read_string()?;
                },
                80 => {
                    self.bool_val = is.read_bool()?;
                },
                90 => {
                    self.bytes_val = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.index != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.index);
        }
        if !self.field.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.field);
        }
        if self.dt != ::protobuf::EnumOrUnknown::new(DataType::str) {
            my_size += ::protobuf::rt::int32_size(3, self.dt.value());
        }
        if self.is_null != false {
            my_size += 1 + 1;
        }
        if self.i32_val != 0 {
            my_size += ::protobuf::rt::int32_size(5, self.i32_val);
        }
        if self.i64_val != 0 {
            my_size += ::protobuf::rt::int64_size(6, self.i64_val);
        }
        if self.f64_val != 0. {
            my_size += 1 + 8;
        }
        if self.f32_val != 0. {
            my_size += 1 + 4;
        }
        if !self.str_val.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.str_val);
        }
        if self.bool_val != false {
            my_size += 1 + 1;
        }
        if !self.bytes_val.is_empty() {
            my_size += ::protobuf::rt::bytes_size(11, &self.bytes_val);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.index != 0 {
            os.write_uint32(1, self.index)?;
        }
        if !self.field.is_empty() {
            os.write_string(2, &self.field)?;
        }
        if self.dt != ::protobuf::EnumOrUnknown::new(DataType::str) {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.dt))?;
        }
        if self.is_null != false {
            os.write_bool(4, self.is_null)?;
        }
        if self.i32_val != 0 {
            os.write_int32(5, self.i32_val)?;
        }
        if self.i64_val != 0 {
            os.write_int64(6, self.i64_val)?;
        }
        if self.f64_val != 0. {
            os.write_double(7, self.f64_val)?;
        }
        if self.f32_val != 0. {
            os.write_float(8, self.f32_val)?;
        }
        if !self.str_val.is_empty() {
            os.write_string(9, &self.str_val)?;
        }
        if self.bool_val != false {
            os.write_bool(10, self.bool_val)?;
        }
        if !self.bytes_val.is_empty() {
            os.write_bytes(11, &self.bytes_val)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Column {
        Column::new()
    }

    fn clear(&mut self) {
        self.index = 0;
        self.field.clear();
        self.dt = ::protobuf::EnumOrUnknown::new(DataType::str);
        self.is_null = false;
        self.i32_val = 0;
        self.i64_val = 0;
        self.f64_val = 0.;
        self.f32_val = 0.;
        self.str_val.clear();
        self.bool_val = false;
        self.bytes_val.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Column {
        static instance: Column = Column {
            index: 0,
            field: ::std::string::String::new(),
            dt: ::protobuf::EnumOrUnknown::from_i32(0),
            is_null: false,
            i32_val: 0,
            i64_val: 0,
            f64_val: 0.,
            f32_val: 0.,
            str_val: ::std::string::String::new(),
            bool_val: false,
            bytes_val: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:transfer.DataType)
pub enum DataType {
    // @@protoc_insertion_point(enum_value:transfer.DataType.str)
    str = 0,
    // @@protoc_insertion_point(enum_value:transfer.DataType.bool)
    bool = 1,
    // @@protoc_insertion_point(enum_value:transfer.DataType.f64)
    f64 = 2,
    // @@protoc_insertion_point(enum_value:transfer.DataType.f32)
    f32 = 3,
    // @@protoc_insertion_point(enum_value:transfer.DataType.i32)
    i32 = 4,
    // @@protoc_insertion_point(enum_value:transfer.DataType.i64)
    i64 = 5,
    // @@protoc_insertion_point(enum_value:transfer.DataType.bytes)
    bytes = 6,
    // @@protoc_insertion_point(enum_value:transfer.DataType.json)
    json = 7,
    // @@protoc_insertion_point(enum_value:transfer.DataType.unknown)
    unknown = 8,
}

impl ::protobuf::Enum for DataType {
    const NAME: &'static str = "DataType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<DataType> {
        match value {
            0 => ::std::option::Option::Some(DataType::str),
            1 => ::std::option::Option::Some(DataType::bool),
            2 => ::std::option::Option::Some(DataType::f64),
            3 => ::std::option::Option::Some(DataType::f32),
            4 => ::std::option::Option::Some(DataType::i32),
            5 => ::std::option::Option::Some(DataType::i64),
            6 => ::std::option::Option::Some(DataType::bytes),
            7 => ::std::option::Option::Some(DataType::json),
            8 => ::std::option::Option::Some(DataType::unknown),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<DataType> {
        match str {
            "str" => ::std::option::Option::Some(DataType::str),
            "bool" => ::std::option::Option::Some(DataType::bool),
            "f64" => ::std::option::Option::Some(DataType::f64),
            "f32" => ::std::option::Option::Some(DataType::f32),
            "i32" => ::std::option::Option::Some(DataType::i32),
            "i64" => ::std::option::Option::Some(DataType::i64),
            "bytes" => ::std::option::Option::Some(DataType::bytes),
            "json" => ::std::option::Option::Some(DataType::json),
            "unknown" => ::std::option::Option::Some(DataType::unknown),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [DataType] = &[
        DataType::str,
        DataType::bool,
        DataType::f64,
        DataType::f32,
        DataType::i32,
        DataType::i64,
        DataType::bytes,
        DataType::json,
        DataType::unknown,
    ];
}

impl ::std::default::Default for DataType {
    fn default() -> Self {
        DataType::str
    }
}

