// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `transfer.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

/// *
///  Row that represent data, including one or more columns, which can represent a data set.
// @@protoc_insertion_point(message:transfer.Row)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Row {
    // message fields
    /// *
    ///  data offset
    // @@protoc_insertion_point(field:transfer.Row.offset)
    pub offset: u64,
    /// *
    ///  include all columns in row data.
    // @@protoc_insertion_point(field:transfer.Row.columns)
    pub columns: ::std::vec::Vec<Column>,
    /// *
    ///  mask value which can indicate the special row data. eg: barrier, EOF and so on.
    // @@protoc_insertion_point(field:transfer.Row.mask)
    pub mask: u32,
    /// *
    ///  source
    // @@protoc_insertion_point(field:transfer.Row.source)
    pub source: ::std::string::String,
    /// *
    ///  raw data
    // @@protoc_insertion_point(field:transfer.Row.raw)
    pub raw: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:transfer.Row.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Row {
    fn default() -> &'a Row {
        <Row as ::protobuf::Message>::default_instance()
    }
}

impl Row {
    pub fn new() -> Row {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "offset",
            |m: &Row| { &m.offset },
            |m: &mut Row| { &mut m.offset },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "columns",
            |m: &Row| { &m.columns },
            |m: &mut Row| { &mut m.columns },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mask",
            |m: &Row| { &m.mask },
            |m: &mut Row| { &mut m.mask },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "source",
            |m: &Row| { &m.source },
            |m: &mut Row| { &mut m.source },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "raw",
            |m: &Row| { &m.raw },
            |m: &mut Row| { &mut m.raw },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Row>(
            "Row",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Row {
    const NAME: &'static str = "Row";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.offset = is.read_uint64()?;
                },
                18 => {
                    self.columns.push(is.read_message()?);
                },
                24 => {
                    self.mask = is.read_uint32()?;
                },
                34 => {
                    self.source = is.read_string()?;
                },
                42 => {
                    self.raw = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.offset != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.offset);
        }
        for value in &self.columns {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.mask != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.mask);
        }
        if !self.source.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.source);
        }
        if !self.raw.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.raw);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.offset != 0 {
            os.write_uint64(1, self.offset)?;
        }
        for v in &self.columns {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.mask != 0 {
            os.write_uint32(3, self.mask)?;
        }
        if !self.source.is_empty() {
            os.write_string(4, &self.source)?;
        }
        if !self.raw.is_empty() {
            os.write_bytes(5, &self.raw)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Row {
        Row::new()
    }

    fn clear(&mut self) {
        self.offset = 0;
        self.columns.clear();
        self.mask = 0;
        self.source.clear();
        self.raw.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Row {
        static instance: Row = Row {
            offset: 0,
            columns: ::std::vec::Vec::new(),
            mask: 0,
            source: ::std::string::String::new(),
            raw: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Row {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Row").unwrap()).clone()
    }
}

impl ::protobuf::reflect::ProtobufValue for Row {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Column struct in each row.
// @@protoc_insertion_point(message:transfer.Column)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Column {
    // message fields
    // @@protoc_insertion_point(field:transfer.Column.index)
    pub index: u32,
    // @@protoc_insertion_point(field:transfer.Column.field)
    pub field: ::std::string::String,
    // @@protoc_insertion_point(field:transfer.Column.dt)
    pub dt: ::protobuf::EnumOrUnknown<DataType>,
    // @@protoc_insertion_point(field:transfer.Column.is_null)
    pub is_null: bool,
    // @@protoc_insertion_point(field:transfer.Column.i32_val)
    pub i32_val: i32,
    // @@protoc_insertion_point(field:transfer.Column.i64_val)
    pub i64_val: i64,
    // @@protoc_insertion_point(field:transfer.Column.f64_val)
    pub f64_val: f64,
    // @@protoc_insertion_point(field:transfer.Column.f32_val)
    pub f32_val: f32,
    // @@protoc_insertion_point(field:transfer.Column.str_val)
    pub str_val: ::std::string::String,
    // @@protoc_insertion_point(field:transfer.Column.bool_val)
    pub bool_val: bool,
    // @@protoc_insertion_point(field:transfer.Column.bytes_val)
    pub bytes_val: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:transfer.Column.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Column {
    fn default() -> &'a Column {
        <Column as ::protobuf::Message>::default_instance()
    }
}

impl Column {
    pub fn new() -> Column {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(11);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "index",
            |m: &Column| { &m.index },
            |m: &mut Column| { &mut m.index },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "field",
            |m: &Column| { &m.field },
            |m: &mut Column| { &mut m.field },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "dt",
            |m: &Column| { &m.dt },
            |m: &mut Column| { &mut m.dt },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_null",
            |m: &Column| { &m.is_null },
            |m: &mut Column| { &mut m.is_null },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "i32_val",
            |m: &Column| { &m.i32_val },
            |m: &mut Column| { &mut m.i32_val },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "i64_val",
            |m: &Column| { &m.i64_val },
            |m: &mut Column| { &mut m.i64_val },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "f64_val",
            |m: &Column| { &m.f64_val },
            |m: &mut Column| { &mut m.f64_val },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "f32_val",
            |m: &Column| { &m.f32_val },
            |m: &mut Column| { &mut m.f32_val },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "str_val",
            |m: &Column| { &m.str_val },
            |m: &mut Column| { &mut m.str_val },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bool_val",
            |m: &Column| { &m.bool_val },
            |m: &mut Column| { &mut m.bool_val },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bytes_val",
            |m: &Column| { &m.bytes_val },
            |m: &mut Column| { &mut m.bytes_val },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Column>(
            "Column",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Column {
    const NAME: &'static str = "Column";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.index = is.read_uint32()?;
                },
                18 => {
                    self.field = is.read_string()?;
                },
                24 => {
                    self.dt = is.read_enum_or_unknown()?;
                },
                32 => {
                    self.is_null = is.read_bool()?;
                },
                40 => {
                    self.i32_val = is.read_int32()?;
                },
                48 => {
                    self.i64_val = is.read_int64()?;
                },
                57 => {
                    self.f64_val = is.read_double()?;
                },
                69 => {
                    self.f32_val = is.read_float()?;
                },
                74 => {
                    self.str_val = is.read_string()?;
                },
                80 => {
                    self.bool_val = is.read_bool()?;
                },
                90 => {
                    self.bytes_val = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.index != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.index);
        }
        if !self.field.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.field);
        }
        if self.dt != ::protobuf::EnumOrUnknown::new(DataType::str) {
            my_size += ::protobuf::rt::int32_size(3, self.dt.value());
        }
        if self.is_null != false {
            my_size += 1 + 1;
        }
        if self.i32_val != 0 {
            my_size += ::protobuf::rt::int32_size(5, self.i32_val);
        }
        if self.i64_val != 0 {
            my_size += ::protobuf::rt::int64_size(6, self.i64_val);
        }
        if self.f64_val != 0. {
            my_size += 1 + 8;
        }
        if self.f32_val != 0. {
            my_size += 1 + 4;
        }
        if !self.str_val.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.str_val);
        }
        if self.bool_val != false {
            my_size += 1 + 1;
        }
        if !self.bytes_val.is_empty() {
            my_size += ::protobuf::rt::bytes_size(11, &self.bytes_val);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.index != 0 {
            os.write_uint32(1, self.index)?;
        }
        if !self.field.is_empty() {
            os.write_string(2, &self.field)?;
        }
        if self.dt != ::protobuf::EnumOrUnknown::new(DataType::str) {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.dt))?;
        }
        if self.is_null != false {
            os.write_bool(4, self.is_null)?;
        }
        if self.i32_val != 0 {
            os.write_int32(5, self.i32_val)?;
        }
        if self.i64_val != 0 {
            os.write_int64(6, self.i64_val)?;
        }
        if self.f64_val != 0. {
            os.write_double(7, self.f64_val)?;
        }
        if self.f32_val != 0. {
            os.write_float(8, self.f32_val)?;
        }
        if !self.str_val.is_empty() {
            os.write_string(9, &self.str_val)?;
        }
        if self.bool_val != false {
            os.write_bool(10, self.bool_val)?;
        }
        if !self.bytes_val.is_empty() {
            os.write_bytes(11, &self.bytes_val)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Column {
        Column::new()
    }

    fn clear(&mut self) {
        self.index = 0;
        self.field.clear();
        self.dt = ::protobuf::EnumOrUnknown::new(DataType::str);
        self.is_null = false;
        self.i32_val = 0;
        self.i64_val = 0;
        self.f64_val = 0.;
        self.f32_val = 0.;
        self.str_val.clear();
        self.bool_val = false;
        self.bytes_val.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Column {
        static instance: Column = Column {
            index: 0,
            field: ::std::string::String::new(),
            dt: ::protobuf::EnumOrUnknown::from_i32(0),
            is_null: false,
            i32_val: 0,
            i64_val: 0,
            f64_val: 0.,
            f32_val: 0.,
            str_val: ::std::string::String::new(),
            bool_val: false,
            bytes_val: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Column {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Column").unwrap()).clone()
    }
}

impl ::protobuf::reflect::ProtobufValue for Column {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Supported data types.
#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:transfer.DataType)
pub enum DataType {
    // @@protoc_insertion_point(enum_value:transfer.DataType.str)
    str = 0,
    // @@protoc_insertion_point(enum_value:transfer.DataType.bool)
    bool = 1,
    // @@protoc_insertion_point(enum_value:transfer.DataType.f64)
    f64 = 2,
    // @@protoc_insertion_point(enum_value:transfer.DataType.f32)
    f32 = 3,
    // @@protoc_insertion_point(enum_value:transfer.DataType.i32)
    i32 = 4,
    // @@protoc_insertion_point(enum_value:transfer.DataType.i64)
    i64 = 5,
    // @@protoc_insertion_point(enum_value:transfer.DataType.bytes)
    bytes = 6,
    // @@protoc_insertion_point(enum_value:transfer.DataType.json)
    json = 7,
    // @@protoc_insertion_point(enum_value:transfer.DataType.unknown)
    unknown = 8,
}

impl ::protobuf::Enum for DataType {
    const NAME: &'static str = "DataType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<DataType> {
        match value {
            0 => ::std::option::Option::Some(DataType::str),
            1 => ::std::option::Option::Some(DataType::bool),
            2 => ::std::option::Option::Some(DataType::f64),
            3 => ::std::option::Option::Some(DataType::f32),
            4 => ::std::option::Option::Some(DataType::i32),
            5 => ::std::option::Option::Some(DataType::i64),
            6 => ::std::option::Option::Some(DataType::bytes),
            7 => ::std::option::Option::Some(DataType::json),
            8 => ::std::option::Option::Some(DataType::unknown),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<DataType> {
        match str {
            "str" => ::std::option::Option::Some(DataType::str),
            "bool" => ::std::option::Option::Some(DataType::bool),
            "f64" => ::std::option::Option::Some(DataType::f64),
            "f32" => ::std::option::Option::Some(DataType::f32),
            "i32" => ::std::option::Option::Some(DataType::i32),
            "i64" => ::std::option::Option::Some(DataType::i64),
            "bytes" => ::std::option::Option::Some(DataType::bytes),
            "json" => ::std::option::Option::Some(DataType::json),
            "unknown" => ::std::option::Option::Some(DataType::unknown),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [DataType] = &[
        DataType::str,
        DataType::bool,
        DataType::f64,
        DataType::f32,
        DataType::i32,
        DataType::i64,
        DataType::bytes,
        DataType::json,
        DataType::unknown,
    ];
}

impl ::protobuf::EnumFull for DataType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("DataType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for DataType {
    fn default() -> Self {
        DataType::str
    }
}

impl DataType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<DataType>("DataType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0etransfer.proto\x12\x08transfer\"\x87\x01\n\x03Row\x12\x16\n\x06off\
    set\x18\x01\x20\x01(\x04R\x06offset\x12*\n\x07columns\x18\x02\x20\x03(\
    \x0b2\x10.transfer.ColumnR\x07columns\x12\x12\n\x04mask\x18\x03\x20\x01(\
    \rR\x04mask\x12\x16\n\x06source\x18\x04\x20\x01(\tR\x06source\x12\x10\n\
    \x03raw\x18\x05\x20\x01(\x0cR\x03raw\"\xa6\x02\n\x06Column\x12\x14\n\x05\
    index\x18\x01\x20\x01(\rR\x05index\x12\x14\n\x05field\x18\x02\x20\x01(\t\
    R\x05field\x12\"\n\x02dt\x18\x03\x20\x01(\x0e2\x12.transfer.DataTypeR\
    \x02dt\x12\x17\n\x07is_null\x18\x04\x20\x01(\x08R\x06isNull\x12\x17\n\
    \x07i32_val\x18\x05\x20\x01(\x05R\x06i32Val\x12\x17\n\x07i64_val\x18\x06\
    \x20\x01(\x03R\x06i64Val\x12\x17\n\x07f64_val\x18\x07\x20\x01(\x01R\x06f\
    64Val\x12\x17\n\x07f32_val\x18\x08\x20\x01(\x02R\x06f32Val\x12\x17\n\x07\
    str_val\x18\t\x20\x01(\tR\x06strVal\x12\x19\n\x08bool_val\x18\n\x20\x01(\
    \x08R\x07boolVal\x12\x1b\n\tbytes_val\x18\x0b\x20\x01(\x0cR\x08bytesVal*\
    c\n\x08DataType\x12\x07\n\x03str\x10\0\x12\x08\n\x04bool\x10\x01\x12\x07\
    \n\x03f64\x10\x02\x12\x07\n\x03f32\x10\x03\x12\x07\n\x03i32\x10\x04\x12\
    \x07\n\x03i64\x10\x05\x12\t\n\x05bytes\x10\x06\x12\x08\n\x04json\x10\x07\
    \x12\x0b\n\x07unknown\x10\x08B\x15\n\x13com.fusionpro.protoJ\xa2\r\n\x06\
    \x12\x04\0\0:\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\
    \x03\x01\0\x11\n\x08\n\x01\x08\x12\x03\x03\0,\n\t\n\x02\x08\x01\x12\x03\
    \x03\0,\ng\n\x02\x04\0\x12\x04\x08\0\x1d\x01\x1a[*\n\x20Row\x20that\x20r\
    epresent\x20data,\x20including\x20one\x20or\x20more\x20columns,\x20which\
    \x20can\x20represent\x20a\x20data\x20set.\n\n\n\n\x03\x04\0\x01\x12\x03\
    \x08\x08\x0b\n\x1c\n\x04\x04\0\x02\0\x12\x03\x0c\x02\x14\x1a\x0f*\n\x20d\
    ata\x20offset\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x0c\x02\x08\n\x0c\n\
    \x05\x04\0\x02\0\x01\x12\x03\x0c\t\x0f\n\x0c\n\x05\x04\0\x02\0\x03\x12\
    \x03\x0c\x12\x13\n1\n\x04\x04\0\x02\x01\x12\x03\x10\x02\x1e\x1a$*\n\x20i\
    nclude\x20all\x20columns\x20in\x20row\x20data.\n\n\x0c\n\x05\x04\0\x02\
    \x01\x04\x12\x03\x10\x02\n\n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03\x10\x0b\
    \x11\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x10\x12\x19\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03\x10\x1c\x1d\n`\n\x04\x04\0\x02\x02\x12\x03\x14\x02\
    \x12\x1aS*\n\x20mask\x20value\x20which\x20can\x20indicate\x20the\x20spec\
    ial\x20row\x20data.\x20eg:\x20barrier,\x20EOF\x20and\x20so\x20on.\n\n\
    \x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x14\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x02\x01\x12\x03\x14\t\r\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x14\x10\
    \x11\n\x17\n\x04\x04\0\x02\x03\x12\x03\x18\x02\x14\x1a\n*\n\x20source\n\
    \n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x18\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x03\x01\x12\x03\x18\t\x0f\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x18\x12\
    \x13\n\x19\n\x04\x04\0\x02\x04\x12\x03\x1c\x02\x10\x1a\x0c*\n\x20raw\x20\
    data\n\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x1c\x02\x07\n\x0c\n\x05\x04\
    \0\x02\x04\x01\x12\x03\x1c\x08\x0b\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\
    \x1c\x0e\x0f\n#\n\x02\x05\0\x12\x04\x20\0*\x01\x1a\x17\x20Supported\x20d\
    ata\x20types.\n\n\n\n\x03\x05\0\x01\x12\x03\x20\x05\r\n\x0b\n\x04\x05\0\
    \x02\0\x12\x03!\x02\n\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03!\x02\x05\n\x0c\
    \n\x05\x05\0\x02\0\x02\x12\x03!\x08\t\n\x0b\n\x04\x05\0\x02\x01\x12\x03\
    \"\x02\x0b\n\x0c\n\x05\x05\0\x02\x01\x01\x12\x03\"\x02\x06\n\x0c\n\x05\
    \x05\0\x02\x01\x02\x12\x03\"\t\n\n\x0b\n\x04\x05\0\x02\x02\x12\x03#\x02\
    \n\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03#\x02\x05\n\x0c\n\x05\x05\0\x02\
    \x02\x02\x12\x03#\x08\t\n\x0b\n\x04\x05\0\x02\x03\x12\x03$\x02\n\n\x0c\n\
    \x05\x05\0\x02\x03\x01\x12\x03$\x02\x05\n\x0c\n\x05\x05\0\x02\x03\x02\
    \x12\x03$\x08\t\n\x0b\n\x04\x05\0\x02\x04\x12\x03%\x02\n\n\x0c\n\x05\x05\
    \0\x02\x04\x01\x12\x03%\x02\x05\n\x0c\n\x05\x05\0\x02\x04\x02\x12\x03%\
    \x08\t\n\x0b\n\x04\x05\0\x02\x05\x12\x03&\x02\n\n\x0c\n\x05\x05\0\x02\
    \x05\x01\x12\x03&\x02\x05\n\x0c\n\x05\x05\0\x02\x05\x02\x12\x03&\x08\t\n\
    \x0b\n\x04\x05\0\x02\x06\x12\x03'\x02\x0c\n\x0c\n\x05\x05\0\x02\x06\x01\
    \x12\x03'\x02\x07\n\x0c\n\x05\x05\0\x02\x06\x02\x12\x03'\n\x0b\n\x0b\n\
    \x04\x05\0\x02\x07\x12\x03(\x02\x0b\n\x0c\n\x05\x05\0\x02\x07\x01\x12\
    \x03(\x02\x06\n\x0c\n\x05\x05\0\x02\x07\x02\x12\x03(\t\n\n\x0b\n\x04\x05\
    \0\x02\x08\x12\x03)\x02\x0e\n\x0c\n\x05\x05\0\x02\x08\x01\x12\x03)\x02\t\
    \n\x0c\n\x05\x05\0\x02\x08\x02\x12\x03)\x0c\r\n(\n\x02\x04\x01\x12\x04-\
    \0:\x01\x1a\x1c\x20Column\x20struct\x20in\x20each\x20row.\n\n\n\n\x03\
    \x04\x01\x01\x12\x03-\x08\x0e\n\x0b\n\x04\x04\x01\x02\0\x12\x03.\x02\x13\
    \n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03.\x02\x08\n\x0c\n\x05\x04\x01\x02\
    \0\x01\x12\x03.\t\x0e\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03.\x11\x12\n\
    \x0b\n\x04\x04\x01\x02\x01\x12\x03/\x02\x13\n\x0c\n\x05\x04\x01\x02\x01\
    \x05\x12\x03/\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03/\t\x0e\n\
    \x0c\n\x05\x04\x01\x02\x01\x03\x12\x03/\x11\x12\n\x0b\n\x04\x04\x01\x02\
    \x02\x12\x030\x02\x12\n\x0c\n\x05\x04\x01\x02\x02\x06\x12\x030\x02\n\n\
    \x0c\n\x05\x04\x01\x02\x02\x01\x12\x030\x0b\r\n\x0c\n\x05\x04\x01\x02\
    \x02\x03\x12\x030\x10\x11\n\x0b\n\x04\x04\x01\x02\x03\x12\x031\x02\x13\n\
    \x0c\n\x05\x04\x01\x02\x03\x05\x12\x031\x02\x06\n\x0c\n\x05\x04\x01\x02\
    \x03\x01\x12\x031\x07\x0e\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x031\x11\
    \x12\n\x0b\n\x04\x04\x01\x02\x04\x12\x033\x02\x14\n\x0c\n\x05\x04\x01\
    \x02\x04\x05\x12\x033\x02\x07\n\x0c\n\x05\x04\x01\x02\x04\x01\x12\x033\
    \x08\x0f\n\x0c\n\x05\x04\x01\x02\x04\x03\x12\x033\x12\x13\n\x0b\n\x04\
    \x04\x01\x02\x05\x12\x034\x02\x14\n\x0c\n\x05\x04\x01\x02\x05\x05\x12\
    \x034\x02\x07\n\x0c\n\x05\x04\x01\x02\x05\x01\x12\x034\x08\x0f\n\x0c\n\
    \x05\x04\x01\x02\x05\x03\x12\x034\x12\x13\n\x0b\n\x04\x04\x01\x02\x06\
    \x12\x035\x02\x15\n\x0c\n\x05\x04\x01\x02\x06\x05\x12\x035\x02\x08\n\x0c\
    \n\x05\x04\x01\x02\x06\x01\x12\x035\t\x10\n\x0c\n\x05\x04\x01\x02\x06\
    \x03\x12\x035\x13\x14\n\x0b\n\x04\x04\x01\x02\x07\x12\x036\x02\x14\n\x0c\
    \n\x05\x04\x01\x02\x07\x05\x12\x036\x02\x07\n\x0c\n\x05\x04\x01\x02\x07\
    \x01\x12\x036\x08\x0f\n\x0c\n\x05\x04\x01\x02\x07\x03\x12\x036\x12\x13\n\
    \x0b\n\x04\x04\x01\x02\x08\x12\x037\x02\x15\n\x0c\n\x05\x04\x01\x02\x08\
    \x05\x12\x037\x02\x08\n\x0c\n\x05\x04\x01\x02\x08\x01\x12\x037\t\x10\n\
    \x0c\n\x05\x04\x01\x02\x08\x03\x12\x037\x13\x14\n\x0b\n\x04\x04\x01\x02\
    \t\x12\x038\x02\x15\n\x0c\n\x05\x04\x01\x02\t\x05\x12\x038\x02\x06\n\x0c\
    \n\x05\x04\x01\x02\t\x01\x12\x038\x07\x0f\n\x0c\n\x05\x04\x01\x02\t\x03\
    \x12\x038\x12\x14\n\x0b\n\x04\x04\x01\x02\n\x12\x039\x02\x17\n\x0c\n\x05\
    \x04\x01\x02\n\x05\x12\x039\x02\x07\n\x0c\n\x05\x04\x01\x02\n\x01\x12\
    \x039\x08\x11\n\x0c\n\x05\x04\x01\x02\n\x03\x12\x039\x14\x16b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(Row::generated_message_descriptor_data());
            messages.push(Column::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(DataType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
