[package]
name = "fusion-script-ts"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
deno_core = "0.409.0"
fusion-derive = { path = "../../fusion-derive" }
fusion-unit-sdk = { path = "../../fusion-unit-sdk" }
tokio = { version = "1.48.0", features = ["full"] }
serde = "1.0.216"
serde_json = "1.0.134"
anyhow = "1.0.100"
linkme = "0.3.35"
mlua = { version = "0.10.2", features = ["lua54", "send", "async"] }
