[package]
name = "fusion-unit-redis"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
fusion-derive = { path = "../../../fusion-derive" }
fusion-streaming = { path = "../../../fusion-streaming" }
fusion-unit-sdk = { path = "../../../fusion-unit-sdk" }
tokio = { version = "1.48.0", features = ["full"] }
serde = "1.0.216"
serde_json = "1.0.134"
protobuf = "3.7.1"
anyhow = "1.0.100"
mlua = { version = "0.10.2", features = ["lua54", "send", "async"] }
tera = "1.20.0"
