[package]
name = "fusion-capability-example"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fusion-unit-sdk = { path = "../../../fusion-unit-sdk" }
tokio = { version = "1.48.0", features = ["sync", "rt", "macros"] }
async-trait = "0.1.83"

[dev-dependencies]
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
