[package]
name = "fusion-streaming"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

[features]
default = ["all"]
all = ["common"]
common = ["http", "excel"]
trace-all = ["trace-physical", "trace-logical"]
http = []
excel = []
trace-physical = []
trace-logical = []

[dependencies]
petgraph = "0.6.5"
serde = { version = "1.0.156" }
serde_json = "1.0.94"
serde_yaml = "0.9.33"
serde_derive = { version = "1.0" }
protobuf = "3.7.1"
tokio = { version = "1.48.0", features = ["full"] }
redis = "0.25.3"
url = "2.5.0"
anyhow = "1.0.86"
mlua = { version = "0.10.2", features = ["lua54", "send", "async"] }
tera = "1.20.0"
chrono = "0.4.39"
async-trait = "0.1.83"
reqwest = { version = "0.12.9", features = ["rustls-tls"] }
lazy_static = "1.5.0"
indexmap = "2.7.1"

socket2 = "0.5.7"
libc = "0.2.155"
rand = { version = "0.8.5", features = [] }
libloading = "0.8.6"
futures = "0.3.31"
log = "0.4.22"
jsonpath-rust = "0.7.3"
itertools = "0.13.0"
uuid = { version = "1.11.0", features = ["v4"] }
linkme = "0.3.35"
deno_core = "0.382.0"

# ================= PROJECT DEPENDENCES START =================
fusion-derive = { path = "../fusion-derive" }
fusion-unit-sdk = { path = "../fusion-unit-sdk" }
fusion-script-ts = { path = "../scripts/fusion-script-ts"}
# ================== PROJECT DEPENDENCES END ==================

[build-dependencies]

[dev-dependencies]
serde = { version = "1.0" }
serde_json = "1.0"
serde_derive = { version = "1.0" }

