[package]
name = "fusion-unit-tests"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
# core graph computing
# unit sdk
fusion-unit-sdk = { path = "../fusion-unit-sdk" }
libloading = "0.8.6"
serde_json = "1.0.134"
# unit extension plugins.
fusion-unit-datafusion = { path = "../fusion-unit-datafusion" }
fusion-unit-excel = {path = "../fusion-unit-excel"}
fusion-unit-ssh = {path = "../fusion-unit-ssh"}

[dependencies.fusion-streaming]
path = "../fusion-streaming"
features = ["common"]

[dev-dependencies]
tokio = "1.42.0"
env_logger = "0.11.6"
